on: 
  push:
    branches: 
      - '*'
name: CI/CD
jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: SonarQube Install
      run: dotnet tool install dotnet-sonarscanner --tool-path ./
    - name: SonarQube Start
      run: ./dotnet-sonarscanner begin /o:ivanjosipovic /k:IvanJosipovic_BlazorTable /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=$SONARQUBE_TOKEN
      env:
        SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100-preview3-014645
    - name: Dotnet Build
      run: dotnet build --configuration Release
    - name: Dotnet Publish
      working-directory: src/BlazorTable.Sample
      run: dotnet publish --configuration Release      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: SonarQube End
      run: ./dotnet-sonarscanner end /d:sonar.login=$SONARQUBE_TOKEN
      env:
        SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to Test
      id: netlify
      uses: ivanjosipovic/actions/cli@master
      with:
        args: deploy --json -d src/BlazorTable.Sample/bin/Release/netstandard2.0/publish/BlazorTable.Sample/dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      uses: ivanjosipovic/actions/cli@master
      with:
        args: deploy --prod --json -d src/BlazorTable.Sample/bin/Release/netstandard2.0/publish/BlazorTable.Sample/dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
